/**
 * Shree Hari Marketing - Official Product Catalog Data
 * Wholesaler & Direct Morbi Distributor | Pune, Maharashtra
 * Founder: Dilip Desai (12+ Years Industry Experience)
 */

export const TILE_CATALOG = [
  // --- IN STOCK: 400x400mm Digital Parking Tiles (Pune Godown) [8 DESIGNS] ---
  {
    id: "stock-park-01",
    name: "Dazzle Punch Surface 400x400mm",
    series: "Digital Parking Series",
    code: "DAZZLE-004",
    category: "parking-stock",
    status: "in-stock",
    size: "400 x 400 mm",
    sizeImperial: "16\" x 16\"",
    thickness: "10-12 mm",
    finish: "3D Textured Punch (Anti-Skid)",
    piecesPerBox: 5,
    coverageSqFt: 8.61,
    weightKg: 18.5,
    image: "assets/tiles/park_page_1.jpg",
    pdfPath: "Availaible in stock/16x16 digital parking tiles 400x400mm.pdf",
    idealFor: "Residential Driveways, Car Parking, Compound Walls, Ramps",
    features: [
      "Heavy Load Bearing",
      "Oil & Stain Resistant",
      "R11 Anti-Skid Grip",
      "Immediate Pune Dispatch"
    ]
  },
  {
    id: "stock-park-02",
    name: "Maker Punch Surface 400x400mm",
    series: "Digital Parking Series",
    code: "MAKER-065",
    category: "parking-stock",
    status: "in-stock",
    size: "400 x 400 mm",
    sizeImperial: "16\" x 16\"",
    thickness: "10-12 mm",
    finish: "Textured Geometric Punch",
    piecesPerBox: 5,
    coverageSqFt: 8.61,
    weightKg: 18.5,
    image: "assets/tiles/park_page_2.jpg",
    pdfPath: "Availaible in stock/16x16 digital parking tiles 400x400mm.pdf",
    idealFor: "Apartment Basements, Commercial Walkways, Villa Porches",
    features: [
      "High Breaking Strength",
      "Weatherproof",
      "Water Absorption < 0.5%",
      "Ready Godown Stock"
    ]
  },
  {
    id: "stock-park-03",
    name: "Dazzle Premium Punch 400x400mm",
    series: "Digital Parking Series",
    code: "DAZZLE-012",
    category: "parking-stock",
    status: "in-stock",
    size: "400 x 400 mm",
    sizeImperial: "16\" x 16\"",
    thickness: "10-12 mm",
    finish: "Dual-Tone Architectural Punch",
    piecesPerBox: 5,
    coverageSqFt: 8.61,
    weightKg: 18.5,
    image: "assets/tiles/park_page_3.jpg",
    pdfPath: "Availaible in stock/16x16 digital parking tiles 400x400mm.pdf",
    idealFor: "Outdoor Patios, Commercial Parking, Walkways, Terraces",
    features: [
      "Scratch & Wear Resistant",
      "R11 Slip Certified",
      "Fast Pune Delivery",
      "Fade-Resistant Inks"
    ]
  },
  {
    id: "stock-park-04",
    name: "Maker Geometric Pattern 400x400mm",
    series: "Digital Parking Series",
    code: "MAKER-088",
    category: "parking-stock",
    status: "in-stock",
    size: "400 x 400 mm",
    sizeImperial: "16\" x 16\"",
    thickness: "10-12 mm",
    finish: "Anti-Skid Grid Punch",
    piecesPerBox: 5,
    coverageSqFt: 8.61,
    weightKg: 18.5,
    image: "assets/tiles/park_page_4.jpg",
    pdfPath: "Availaible in stock/16x16 digital parking tiles 400x400mm.pdf",
    idealFor: "Heavy Vehicular Parking, Driveways, Industrial Corridors",
    features: [
      "Maximum Traction",
      "Frost Resistant",
      "High Compressive Strength",
      "Direct Pune Godown Stock"
    ]
  },
  {
    id: "stock-park-05",
    name: "Dazzle Textured Slate 400x400mm",
    series: "Digital Parking Series",
    code: "DAZZLE-034",
    category: "parking-stock",
    status: "in-stock",
    size: "400 x 400 mm",
    sizeImperial: "16\" x 16\"",
    thickness: "10-12 mm",
    finish: "Natural Slate Relief (Anti-Slip)",
    piecesPerBox: 5,
    coverageSqFt: 8.61,
    weightKg: 18.5,
    image: "assets/tiles/park_page_5.jpg",
    pdfPath: "Availaible in stock/16x16 digital parking tiles 400x400mm.pdf",
    idealFor: "Garden Pathways, Swimming Pool Decks, Farmhouses",
    features: [
      "Organic Stone Texture",
      "Zero Maintenance",
      "Chemical Proof",
      "Available for Immediate Tempo Loading"
    ]
  },
  {
    id: "stock-park-06",
    name: "Maker Multi-Square Punch 400x400mm",
    series: "Digital Parking Series",
    code: "MAKER-102",
    category: "parking-stock",
    status: "in-stock",
    size: "400 x 400 mm",
    sizeImperial: "16\" x 16\"",
    thickness: "10-12 mm",
    finish: "Cobblestone Punch Pattern",
    piecesPerBox: 5,
    coverageSqFt: 8.61,
    weightKg: 18.5,
    image: "assets/tiles/park_page_6.jpg",
    pdfPath: "Availaible in stock/16x16 digital parking tiles 400x400mm.pdf",
    idealFor: "Boutique Bungalows, Resort Parking, Courtyards",
    features: [
      "Classic Paving Look",
      "Heavy Load Certified",
      "Non-Porous Surface",
      "Same-Day Dispatch"
    ]
  },
  {
    id: "stock-park-07",
    name: "Dazzle Granito Punch 400x400mm",
    series: "Digital Parking Series",
    code: "DAZZLE-055",
    category: "parking-stock",
    status: "in-stock",
    size: "400 x 400 mm",
    sizeImperial: "16\" x 16\"",
    thickness: "10-12 mm",
    finish: "Granite Specks Textured Punch",
    piecesPerBox: 5,
    coverageSqFt: 8.61,
    weightKg: 18.5,
    image: "assets/tiles/park_page_7.jpg",
    pdfPath: "Availaible in stock/16x16 digital parking tiles 400x400mm.pdf",
    idealFor: "Hospital Driveways, Society Parking, Service Stations",
    features: [
      "High Dirt Masking",
      "R11 Grip Level",
      "Thermal Resistant",
      "Direct Wholesaler Pricing"
    ]
  },
  {
    id: "stock-park-08",
    name: "Maker Industrial Punch 400x400mm",
    series: "Digital Parking Series",
    code: "MAKER-124",
    category: "parking-stock",
    status: "in-stock",
    size: "400 x 400 mm",
    sizeImperial: "16\" x 16\"",
    thickness: "10-12 mm",
    finish: "Deep Chevron Anti-Skid Punch",
    piecesPerBox: 5,
    coverageSqFt: 8.61,
    weightKg: 18.5,
    image: "assets/tiles/park_page_8.jpg",
    pdfPath: "Availaible in stock/16x16 digital parking tiles 400x400mm.pdf",
    idealFor: "Ramps with High Incline, Car Washing Bays, Workshops",
    features: [
      "Maximum Wet Grip",
      "Extreme Durability",
      "Chemical & Oil Proof",
      "Instant Godown Pickup"
    ]
  },

  // --- IN STOCK: 600x600mm Porcelain GVT Vitrified Tiles (Pune Godown) [18 DESIGNS] ---
  {
    id: "stock-gvt-01",
    name: "Alabaster White Onyx 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-ALAB-01",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "High-Gloss Mirror Polish",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_0.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Living Rooms, Master Bedrooms, Corporate Reception, Showrooms",
    features: [
      "Italian Onyx Veining",
      "Nano-Polish Stain Guard",
      "Rectified Seamless Edges",
      "In Stock at Pune Godown"
    ]
  },
  {
    id: "stock-gvt-02",
    name: "Statuario Gold Vein 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-STAT-02",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Gloss Glazed Vitrified",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_1.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Premium Living Areas, Feature Walls, Luxury Villas",
    features: [
      "Classic Italian Marble Bookmatch",
      "Super White Porcelain Body",
      "High Scratch Resistance",
      "Direct Pune Wholesale"
    ]
  },
  {
    id: "stock-gvt-03",
    name: "Armani Grey Marble 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-ARMN-03",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Satin Matt Silken Touch",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_2.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Contemporary Living, Modern Kitchens, Boutique Offices",
    features: [
      "Minimalist Grey Texture",
      "Non-Reflective Velvet Touch",
      "Easy Cleaning",
      "Pune Warehouse Stock"
    ]
  },
  {
    id: "stock-gvt-04",
    name: "Crema Marfil Classic 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-CREM-04",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "High-Gloss Polished Glazed",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_3.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Warm Traditional Interiors, Dining Halls, Hallways",
    features: [
      "Warm Beige Spanish Tone",
      "Reflective Depth",
      "Zero Porosity",
      "Ready Stock in Pune"
    ]
  },
  {
    id: "stock-gvt-05",
    name: "Travertine Silver Matt 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-TRAV-05",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Textured Natural Travertine Matt",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_4.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Bathrooms, Balconies, Architectural Foyers, Terraces",
    features: [
      "Linear Sediment Pattern",
      "Anti-Slip R9 Rating",
      "Acid & Alkali Resistant",
      "Fast Local Dispatch"
    ]
  },
  {
    id: "stock-gvt-06",
    name: "Nero Marquina Black 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-NERO-06",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Deep Jet Gloss with White Veining",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_5.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Luxury Powder Rooms, Accent Borders, Executive Suites",
    features: [
      "High-Contrast White Veins",
      "Deep Pigment Lock",
      "Zero Fading",
      "Direct Wholesaler Supply"
    ]
  },
  {
    id: "stock-gvt-07",
    name: "Botticino Fiorito Beige 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-BOTT-07",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "High-Gloss Mirror Finish",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_6.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Flats, Bungalows, Commercial Offices, Clinics",
    features: [
      "Timeless Floral Veining",
      "Ultra-Bright Polish",
      "Wear Class PEI 4",
      "Pune Warehouse Stock"
    ]
  },
  {
    id: "stock-gvt-08",
    name: "Calacatta Gold Royale 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-CALA-08",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Polished Glazed Vitrified",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_7.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Grand Living Rooms, Duplex Staircases, Hotel Lobbies",
    features: [
      "Warm Amber & Grey Veins",
      "Superior Clarity",
      "Thermal Shock Proof",
      "Same-Day Pickup"
    ]
  },
  {
    id: "stock-gvt-09",
    name: "Cement Concrete Charcoal 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-CMNT-09",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Raw Architectural Concrete Matt",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_8.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Industrial Lofts, Cafes, Modern Showrooms, Studios",
    features: [
      "Industrial Raw Texture",
      "Scratch & Footfall Proof",
      "Non-Glaring Surface",
      "Pune Godown Inventory"
    ]
  },
  {
    id: "stock-gvt-10",
    name: "Breccia Aurora Coral 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-BREC-10",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Mirror Polish Glazed",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_9.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Bedrooms, Banquet Spaces, Residential Flats",
    features: [
      "Natural Fossil Specks",
      "Nano-Sealed Porcelain",
      "Stain Resistant",
      "Ready Wholesale Stock"
    ]
  },
  {
    id: "stock-gvt-11",
    name: "Smoke Cloud Grey 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-SMOK-11",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Soft Satin Satin Finish",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_10.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Modern Minimalist Homes, Corporate Cabins, Spas",
    features: [
      "Soft Cloudy Shading",
      "Comfort Underfoot",
      "Low Glare",
      "Direct Pune Delivery"
    ]
  },
  {
    id: "stock-gvt-12",
    name: "Pure Alpine White Gloss 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-ALPN-12",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Ultra-High Gloss Snow White",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_11.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Hospitals, Laboratories, Showrooms, Clean Rooms",
    features: [
      "Pure Solid White Index",
      "Bacterial Resistant Glaze",
      "Reflective Light Maximizer",
      "Available for Bulk Tempo"
    ]
  },
  {
    id: "stock-gvt-13",
    name: "Desert Sand Travertine 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-SAND-13",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Honed Matt Stone Touch",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_12.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Resort Walkways, Semi-Covered Sit-Outs, Balconies",
    features: [
      "Warm Earthy Texture",
      "Anti-Slip Certified",
      "UV Color Fast",
      "Direct Godown Stock"
    ]
  },
  {
    id: "stock-gvt-14",
    name: "Pietra Grey Polished 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-PIET-14",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "High-Gloss Mirror Vitrified",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_13.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Modern Living Areas, Kitchen Flooring, Boutiques",
    features: [
      "Fine White Calcite Veins",
      "Deep Charcoal Base",
      "High Gloss Retention",
      "Pune Warehouse Ready"
    ]
  },
  {
    id: "stock-gvt-15",
    name: "Onyx Verde Jade 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-VERD-15",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Translucent-Look High Gloss",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_14.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Mandir Backdrops, Luxury Bathrooms, Accent Panels",
    features: [
      "Exotic Jade Onyx Glow",
      "Glass-Like Smooth Polish",
      "Stain Guard Sealed",
      "Instant Local Dispatch"
    ]
  },
  {
    id: "stock-gvt-16",
    name: "Rustic Wood Natural Oak 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-WOOD-16",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Wood Grain Relief Matt",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_15.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Bedrooms, Balconies, Farmhouse Cottages, Lounges",
    features: [
      "Authentic Oak Timber Grain",
      "Water & Termite Proof",
      "Warm Wooden Ambience",
      "Stocked at Beldare Patil Depot"
    ]
  },
  {
    id: "stock-gvt-17",
    name: "Carrara Cloud White 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-CARR-17",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Satin Silk Smooth Polish",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_16.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Flats, Bathrooms, Kitchen Walls, Light Commercial",
    features: [
      "Subtle Feathery Veining",
      "Velvet Satin Touch",
      "Scratch Resistant",
      "Pune Warehouse Supply"
    ]
  },
  {
    id: "stock-gvt-18",
    name: "Granite Gris Heavy Matt 600x600mm",
    series: "Porcelain GVT Series",
    code: "GVT-GRAN-18",
    category: "porcelain-stock",
    status: "in-stock",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "9-10 mm",
    finish: "Granite Micro-Textured Matt",
    piecesPerBox: 4,
    coverageSqFt: 15.50,
    weightKg: 28.0,
    image: "assets/tiles/porc_page_17.jpg",
    pdfPath: "Availaible in stock/2x2 porceliane tiles 600x600mm.pdf",
    idealFor: "Corridors, Society Staircases, Office Lift Lobbies",
    features: [
      "Commercial Grade Anti-Wear",
      "Zero Maintenance Matt",
      "Slip Resistant",
      "Ready Pune Stock"
    ]
  },

  // --- BY ORDER: 400x400mm 16mm Heavy Duty Parking (Morbi Direct Supply) ---
  {
    id: "order-16mm-01",
    name: "FRITA 16mm Ultra Heavy-Duty Parking (Vol 3)",
    catalogName: "16mm Morbi Ultra Heavy-Duty Parking Tiles Catalog (Vol 3)",
    catalogNameHi: "16mm मोर्बी अल्ट्रा हेवी-ड्यूटी पार्किंग टाइल्स कैटलॉग (Vol 3)",
    series: "16mm Full Heavy Vitrified",
    code: "FRITA-16MM-V3",
    category: "order-16mm",
    status: "by-order",
    size: "400 x 400 mm",
    sizeImperial: "16\" x 16\"",
    thickness: "16 mm Industrial Grade",
    finish: "Deep Anti-Slip Industrial Punch",
    piecesPerBox: 4,
    coverageSqFt: 6.88,
    weightKg: 24.5,
    image: "assets/catalog/order_400_vol3.jpg",
    pdfPath: "whatsapp",
    idealFor: "Commercial Basements, Petrol Stations, Bus Terminals, Logistics Yards, Ramps",
    features: ["Massive 16mm Slab Body", "Withstands 30+ Ton Trucks", "High MOR > 45 N/mm²", "Direct Morbi Factory Pricing"]
  },
  {
    id: "order-16mm-02",
    name: "FRITA 16mm Heavy Vitrified Parking (Vol 2)",
    catalogName: "16mm Morbi Heavy Vitrified Parking Tiles Catalog (Vol 2)",
    catalogNameHi: "16mm मोर्बी हेवी विट्रीफाइड पार्किंग टाइल्स कैटलॉग (Vol 2)",
    series: "16mm Full Heavy Vitrified",
    code: "FRITA-16MM-V2",
    category: "order-16mm",
    status: "by-order",
    size: "400 x 400 mm",
    sizeImperial: "16\" x 16\"",
    thickness: "16 mm Industrial Grade",
    finish: "Multi-Groove Geo Punch",
    piecesPerBox: 4,
    coverageSqFt: 6.88,
    weightKg: 24.5,
    image: "assets/catalog/order_400_vol2.jpg",
    pdfPath: "whatsapp",
    idealFor: "Industrial Warehouses, Heavy Vehicular Driveways, High Traffic Malls",
    features: ["Extreme Impact Resistance", "Chemical Resistant Glaze", "Direct FTL Logistics", "Custom Factory Orders"]
  },

  // --- BY ORDER: 600x600mm 12mm Heavy Parking & Outdoor (Morbi Direct Supply) ---
  {
    id: "order-12mm-cemanto",
    name: "FRITA Cemanto Series 600x600mm (12mm)",
    catalogName: "FRITA Cemanto Series 12mm Outdoor Vitrified Catalog",
    catalogNameHi: "FRITA सीमेंटो सीरीज 12mm आउटडोर विट्रीफाइड कैटलॉग",
    series: "12mm Outdoor Vitrified",
    code: "CEM-001 to 012",
    category: "order-12mm",
    status: "by-order",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "12 mm Heavy Duty",
    finish: "Micro-Textured Concrete Finish",
    piecesPerBox: 3,
    coverageSqFt: 11.62,
    weightKg: 29.5,
    image: "assets/catalog/order_cemanto.jpg",
    pdfPath: "whatsapp",
    idealFor: "Architectural Courtyards, Rooftop Cafes, Clubhouses, Luxury Driveways",
    features: ["Raw Concrete Aesthetic", "12mm Heavy Body", "Zero Water Absorption", "Morbi Direct Supply"]
  },
  {
    id: "order-12mm-stone",
    name: "FRITA Stone Series 600x600mm (12mm)",
    catalogName: "FRITA Stone Series 12mm Natural Outdoor Catalog",
    catalogNameHi: "FRITA स्टोन सीरीज 12mm नेचुरल आउटडोर कैटलॉग",
    series: "12mm Outdoor Vitrified",
    code: "STONE-01 to 14",
    category: "order-12mm",
    status: "by-order",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "12 mm Heavy Duty",
    finish: "Natural Slate & River Stone Relief",
    piecesPerBox: 3,
    coverageSqFt: 11.62,
    weightKg: 29.5,
    image: "assets/catalog/order_stone.jpg",
    pdfPath: "whatsapp",
    idealFor: "Villas, Swimming Pool Decks, Landscape Stepping, Terraces",
    features: ["Natural Quartz Look", "R12 Wet Slip Grip", "Anti-Algae Coated", "Direct Project Freight"]
  },
  {
    id: "order-12mm-nero",
    name: "FRITA Nero Charcoal Series 600x600mm",
    catalogName: "FRITA Nero Charcoal 12mm Heavy Vitrified Catalog",
    catalogNameHi: "FRITA नीरो चारकोल 12mm हेवी विट्रीफाइड कैटलॉग",
    series: "12mm Outdoor Vitrified",
    code: "NERO-BLACK-01",
    category: "order-12mm",
    status: "by-order",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "12 mm Heavy Duty",
    finish: "Deep Jet Black & Anthracite Grip",
    piecesPerBox: 3,
    coverageSqFt: 11.62,
    weightKg: 29.5,
    image: "assets/catalog/order_nero.jpg",
    pdfPath: "whatsapp",
    idealFor: "High-End Modern Villas, Hotel Entrances, Commercial Plazas",
    features: ["Deep Solid Black Pigment", "UV Sun Proof", "Heavy Vehicle Capable", "Wholesale Bulk Dispatch"]
  },
  {
    id: "order-12mm-sugar",
    name: "FRITA Sugar Outdoor 600x600mm (12mm)",
    catalogName: "FRITA Sugar Sparkle 12mm Outdoor Vitrified Catalog",
    catalogNameHi: "FRITA शुगर स्पार्कल 12mm आउटडोर विट्रीफाइड कैटलॉग",
    series: "12mm Outdoor Vitrified",
    code: "SUGAR-OUTDOOR",
    category: "order-12mm",
    status: "by-order",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "12 mm Heavy Duty",
    finish: "Sugar Grain Anti-Slip Glaze",
    piecesPerBox: 3,
    coverageSqFt: 11.62,
    weightKg: 29.5,
    image: "assets/catalog/order_sugar.jpg",
    pdfPath: "whatsapp",
    idealFor: "Balconies, Porches, Commercial Walkways, Covered Parking",
    features: ["Sparkling Visual Texture", "Tactile Grip Under Foot", "Stain Resisting Seal", "Morbi FTL Pricing"]
  },
  {
    id: "order-12mm-eva",
    name: "FRITA Eva Designer Series 600x600mm",
    catalogName: "FRITA Eva Designer 12mm Outdoor Series Catalog",
    catalogNameHi: "FRITA ईवा डिजाइनर 12mm आउटडोर सीरीज कैटलॉग",
    series: "12mm Outdoor Vitrified",
    code: "EVA-SERIES",
    category: "order-12mm",
    status: "by-order",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "12 mm Heavy Duty",
    finish: "Geometric Designer Accent",
    piecesPerBox: 3,
    coverageSqFt: 11.62,
    weightKg: 29.5,
    image: "assets/catalog/order_eva.jpg",
    pdfPath: "whatsapp",
    idealFor: "Boutique Resorts, Rooftop Lounges, Villa Patios",
    features: ["Designer Geometric Motif", "Scratch Resistant", "Full Outdoor Grade", "Morbi Factory Order"]
  },
  {
    id: "order-12mm-punch",
    name: "FRITA New Punch High-Grip Series",
    catalogName: "FRITA New Punch 12mm High-Grip Parking Catalog",
    catalogNameHi: "FRITA न्यू पंच 12mm हाई-ग्रिप पार्किंग कैटलॉग",
    series: "12mm Outdoor Vitrified",
    code: "PUNCH-EXTREME",
    category: "order-12mm",
    status: "by-order",
    size: "600 x 600 mm",
    sizeImperial: "24\" x 24\"",
    thickness: "12 mm Heavy Duty",
    finish: "Aggressive Multi-Punch Grip",
    piecesPerBox: 3,
    coverageSqFt: 11.62,
    weightKg: 29.5,
    image: "assets/catalog/order_punch.jpg",
    pdfPath: "whatsapp",
    idealFor: "Steep Basements Ramps, Car Washes, Industrial Loading Bays",
    features: ["Maximum Anti-Skid Security", "Heavy Tonnage Certified", "Thermal Shock Proof", "Factory Wholesale"]
  }
];

export const COMPANY_INFO = {
  brandName: "SHREE HARI MARKETING",
  legalName: "SHRI HARI MARKETING",
  proprietor: "Dilip Desai (Dilipbhai Parsotambhai Desai)",
  experience: "12+ Years in Pune Ceramic Tiles Wholesale",
  phone: "9021560608",
  phoneFormatted: "+91 90215 60608",
  phoneClean: "919021560608",
  email: "dilipdesai6060@gmail.com",
  address: "Mumbai Katraj Highway Near Bramha Hotel, Beldare Patil Warehouse, Sarve No 60, Ambegaon, Pune 411046, Maharashtra, India",
  coordinates: "18.45421293060824, 73.83213047085272",
  googleMapsUrl: "https://maps.app.goo.gl/pzh3uj48oDYiQY2a7",
  gstin: "27AXKPD0028L1ZK",
  gstPdf: "Certificate/DOC-20250716-WA0031..pdf",
  shopActPdf: "Certificate/SHOP ACT CERTIFICATE.pdf",
  udyamPdf: "Certificate/Print _ Udyam Registration Certificate.pdf"
};

/**
 * Senior Engineered Defensive Immutability (Deep Freeze)
 * Prevents prototype pollution, runtime state poisoning, and rogue extension tampering.
 */
export function deepFreeze(obj) {
  if (obj === null || typeof obj !== 'object') return obj;
  Object.freeze(obj);
  Object.getOwnPropertyNames(obj).forEach(prop => {
    const val = obj[prop];
    if (val !== null && (typeof val === 'object' || typeof val === 'function') && !Object.isFrozen(val)) {
      deepFreeze(val);
    }
  });
  return obj;
}

// Pre-compute search string before freezing to eliminate in-memory mutation in controllers
TILE_CATALOG.forEach(t => {
  t._searchStr = `${t.name} ${t.code} ${t.finish} ${t.series} ${t.idealFor}`.toLowerCase();
});

deepFreeze(TILE_CATALOG);
deepFreeze(COMPANY_INFO);
